/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module cla(a, b, cin, sum, carry);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  input [3:0] a;
  wire [3:0] a;
  input [3:0] b;
  wire [3:0] b;
  output carry;
  wire carry;
  input cin;
  wire cin;
  output [3:0] sum;
  wire [3:0] sum;
  sky130_fd_sc_hd__xnor2_1 _07_ (
    .A(b[0]),
    .B(a[0]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__maj3_1 _08_ (
    .A(b[0]),
    .B(a[0]),
    .C(cin),
    .X(_01_)
  );
  sky130_fd_sc_hd__xnor2_1 _09_ (
    .A(b[1]),
    .B(a[1]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__maj3_1 _10_ (
    .A(b[1]),
    .B(a[1]),
    .C(_01_),
    .X(_03_)
  );
  sky130_fd_sc_hd__xnor2_1 _11_ (
    .A(b[2]),
    .B(a[2]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__maj3_1 _12_ (
    .A(b[2]),
    .B(a[2]),
    .C(_03_),
    .X(_05_)
  );
  sky130_fd_sc_hd__xnor2_1 _13_ (
    .A(b[3]),
    .B(a[3]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__maj3_1 _14_ (
    .A(b[3]),
    .B(a[3]),
    .C(_05_),
    .X(carry)
  );
  sky130_fd_sc_hd__xnor2_1 _15_ (
    .A(cin),
    .B(_00_),
    .Y(sum[0])
  );
  sky130_fd_sc_hd__xnor2_1 _16_ (
    .A(_01_),
    .B(_02_),
    .Y(sum[1])
  );
  sky130_fd_sc_hd__xnor2_1 _17_ (
    .A(_03_),
    .B(_04_),
    .Y(sum[2])
  );
  sky130_fd_sc_hd__xnor2_1 _18_ (
    .A(_05_),
    .B(_06_),
    .Y(sum[3])
  );
endmodule
