/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "FA.v:1.1-4.10" *)
module FA(a_in, b_in, c_in, sum, carry);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "FA.v:1.17-1.21" *)
  input a_in;
  wire a_in;
  (* src = "FA.v:1.23-1.27" *)
  input b_in;
  wire b_in;
  (* src = "FA.v:1.29-1.33" *)
  input c_in;
  wire c_in;
  (* src = "FA.v:1.47-1.52" *)
  output carry;
  wire carry;
  (* src = "FA.v:1.42-1.45" *)
  output sum;
  wire sum;
  NOR2_X1 _3_ (
    .A1(b_in),
    .A2(c_in),
    .ZN(_0_)
  );
  XNOR2_X1 _4_ (
    .A(b_in),
    .B(c_in),
    .ZN(_1_)
  );
  XNOR2_X1 _5_ (
    .A(a_in),
    .B(_1_),
    .ZN(sum)
  );
  AOI21_X1 _6_ (
    .A(a_in),
    .B1(c_in),
    .B2(b_in),
    .ZN(_2_)
  );
  NOR2_X1 _7_ (
    .A1(_0_),
    .A2(_2_),
    .ZN(carry)
  );
endmodule
